jdk:
  - oraclejdk8
language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.0
    - android-22
    - extra-android-m2repository
    - extra-android-support
branches:
  only:
    - master
script:
  - gradle -version
  - gradle jacocoTestReport coveralls