language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository
    - extra-android-support

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

#env:
#  global:
#    - COVERALLS_REPO_TOKEN=qqeJnWXRN3vRFgg5qKPiRO5jEqc3DOcSm

#before_script:
#    - ./gradlew clean checkstyle

script:
    - ./gradlew test coveralls --debug

notifications:
  email: false