language: android

addons:
    apt:
      packages:
        - oracle-java8-installer

before_install:
    - remove_dir_from_path $JAVA_HOME/bin
    - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - export PATH=$JAVA_HOME/bin:$PATH
    - java -version

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-26
    - extra-android-m2repository
    - extra-android-support

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

#env:
#  global:
#before_script:
#    - ./gradlew clean checkstyle

script:
    - ./gradlew test coveralls

notifications:
  email: false